### ISSUE TITLE
VLC icon doesn't work for me

### ISSUE THREAD

**Issue by forteller** [Frostbitten-jello/Skeuowaita#18]
Hi. Thanks for the new icons! :D 

Unfortunately I can't get the VLC one to work. The other new ones shows up, but not the VLC one, even though I've checked that I have it. My VLC is installed trough rpmfusion, and I'm running Nobara Linux (based on Fedora).

Thanks!

**Comment by Frostbitten-jello** [comment]
@forteller It happens because the different repositories and distros have their icons with different names. You can tell me what the icon name is in RPM fusion and I will add the icon with that name. Just go inside `/usr/share/applications` and look for the `.desktop` file for VLC and inside it there is the name of the icon file with the line `Icon=<name of the icon file>`.

**Comment by Frostbitten-jello** [comment]
@forteller added the icon, update the theme n let me know if it works :)

**Comment by forteller** [comment]
Yes, it did! Thanks so much!
